### ISSUE TITLE
Build fails when using RedHat devtoolset

### ISSUE THREAD

**Issue by feedhandler** [ja11sop/cuppa#19]
seems to be some toolchain detection problem when the RedHat devtoolset is used. 
Build is OK with CentOS 7 default compiler, gcc 4.8.5:
```
root@711972d45ad7> g++ -dumpversion
4.8.5
root@711972d45ad7> scons
scons: Reading SConscript files ...
cuppa: version: [info] cuppa: version 0.9.21
cuppa: core: [info] using sconstruct file [SConstruct]
cuppa: configure: [info] No settings to load, skipping configure
Could not detect the version of libc installed. You might be missing some development libraries!
cuppa: core: [info] available toolchains are ['gcc48', 'gcc']
cuppa: core: [info] Using sub-sconscripts ['./src/SConscript']
scons: done reading SConscript files.
scons: Building targets ...
Progress( SconstructBegin )
Progress( Begin sconscript: [./src/SConscript] )
Progress( Starting variant: [_build/src/gcc48/dbg/x86_64/c++1y] )
g++ -o _build/src/gcc48/dbg/x86_64/c++1y/working/_build/src/gcc48/dbg/x86_64/c++1y/working/hello.o -c -std=c++1y -fexceptions -Wall -g -rdynamic -I. -I_build/src/gcc48/dbg/x86_64/c++1y/working -Isrc -I_build/src/gcc48/dbg/x86_64/c++1y/working/src -Isrc/src src/hello.cpp
g++ -o _build/src/gcc48/dbg/x86_64/c++1y/final/hello -Wl,-rpath=. _build/src/gcc48/dbg/x86_64/c++1y/working/_build/src/gcc48/dbg/x86_64/c++1y/working/hello.o -Xlinker -Bstatic -Xlinker -Bdynamic -lpthread -lrt
Progress( Finished variant: [_build/src/gcc48/dbg/x86_64/c++1y] )
Progress( End sconscript: [./src/SConscript] )
Progress( SconstructEnd )
scons: done building targets.
root@711972d45ad7> 
```
Enable the devtoolset, gcc is upgraded to 6.2.1:
```
root@711972d45ad7> source /opt/rh/devtoolset-6/enable 
root@711972d45ad7> g++ -dumpversion
6.2.1
root@711972d45ad7> 
```
Now the build fails:
```
root@711972d45ad7> scons
scons: Reading SConscript files ...
cuppa: version: [info] cuppa: version 0.9.21
cuppa: core: [info] using sconstruct file [SConstruct]
cuppa: configure: [info] No settings to load, skipping configure
Could not detect the version of libc installed. You might be missing some development libraries!
cuppa: core: [info] available toolchains are ['gcc62', 'gcc']
cuppa: core: [info] Using sub-sconscripts ['./src/SConscript']
scons: done reading SConscript files.
scons: Building targets ...
Progress( SconstructBegin )
Progress( Begin sconscript: [./src/SConscript] )
Progress( Starting variant: [_build/src/gcc62/dbg/x86_64/c++1z] )
g++ -o _build/src/gcc62/dbg/x86_64/c++1z/working/_build/src/gcc62/dbg/x86_64/c++1z/working/hello.o -c -std=c++1z -fexceptions -Wall -g -rdynamic -I. -I_build/src/gcc62/dbg/x86_64/c++1z/working -Isrc -I_build/src/gcc62/dbg/x86_64/c++1z/working/src -Isrc/src src/hello.cpp
g++: error: unrecognized command line option '-std=c++1z'
 === Process Terminated with status 1 (Elapsed 0.413326978683s) === 

scons: *** [_build/src/gcc62/dbg/x86_64/c++1z/working/_build/src/gcc62/dbg/x86_64/c++1z/working/hello.o] Error 1
scons: building terminated because of errors.
root@711972d45ad7> 
```
Seems like it has detected the upgraded gcc but something has got confused with the compile flags.

NB a workaround is to use the old scons trick and just import the environment path into the build environment:
```
env['ENV']['PATH'] = os.environ['PATH'];
```

**Comment by ja11sop** [comment]
This is really an issue with how RH relies on environment values to pull in the "right" compiler. Under the hood Cuppa will spawn processes to run the compilation. Cuppa relies heavily on ensuring a clean environment so you know exactly what you are building with and what you aren't. What essentially we are being forced to do is capture the surrounding environment of which we have no control and then pull all variables from that current environment and then inject those (blind) into subprocess calls and hope that will be repeatable. It could be we have no choice on RH. Windows has similar problems where we specifically spawn particular subprocesses with particular environment variables set.

I wonder would a specific approach be possible just for RH and presumably derivatives that adopt this somewhat flawed model. That might make this transparent. I'd need to investigate a little more to see if that can be achieved.

**Comment by ja11sop** [comment]
Can you try the latest version of Cuppa passing `--propagate-env` and see if that works for you?

**Comment by ja11sop** [comment]
See also the new option that allows propagation of `PATH` only: `--propagate-path`

**Comment by ja11sop** [comment]
Fixed in `0.9.24`

**Comment by feedhandler** [comment]
Sorry for delayed reply. I just tried this with 0.9.24 but it still fails:
```
dmsdev@dmsdev> scons --offline --boost-location=~/Downloads/boost_1_64_0.tar.gz --propagate-env
scons: Reading SConscript files ...
cuppa: version: [info] cuppa: version 0.9.24
cuppa: core: [info] Running in OFFLINE mode
cuppa: core: [info] using sconstruct file [SConstruct]
cuppa: configure: [info] No settings to load, skipping configure
Could not detect the version of libc installed. You might be missing some development libraries!
cuppa: core: [info] available toolchains are ['gcc62', 'gcc']
cuppa: core: [info] default profiles are ['']
cuppa: core: [info] default dependencies are ['boost', 'quickfix']
cuppa: core: [info] Using sub-sconscripts ['./src/SConscript']
cuppa: core: [info] Default variants of ['dbg'] being used.
scons: done reading SConscript files.
scons: Building targets ...
Progress( SconstructBegin )
Progress( Begin sconscript: [./src/SConscript] )
Progress( Starting variant: [_build/src/gcc62/dbg/x86_64/c++1z] )
g++ -o _build/src/gcc62/dbg/x86_64/c++1z/working/_build/src/gcc62/dbg/x86_64/c++1z/working/Main.o -c -std=c++1z -fexceptions -Wall -g -rdynamic -DBOOST_PARAMETER_MAX_ARITY=20 -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -isystem/home/dmsdev/quickfix-install2/include -isystem_cuppa/boost_1_64_0/clean -I. -I_build/src/gcc62/dbg/x86_64/c++1z/working -Isrc -I_build/src/gcc62/dbg/x86_64/c++1z/working/src -Isrc/src src/Main.cpp
g++: error: unrecognized command line option ‘-std=c++1z’
 === Process Terminated with status 1 (Elapsed 0.0121519565582s) === 

scons: *** [_build/src/gcc62/dbg/x86_64/c++1z/working/_build/src/gcc62/dbg/x86_64/c++1z/working/Main.o] Error 1
scons: building terminated because of errors.
dmsdev@dmsdev> 
```
(same also with --propagate-path)

**Comment by ja11sop** [comment]
Ok - let's see if we can get to the bottom of this. It seems like this is not `env` based.

**Comment by ja11sop** [comment]
Can you try running this as before but with `--verbosity=debug`?

**Comment by feedhandler** [comment]
Sure, here you go:
```
dmsdev@dmsdev> scons --offline --propagate-env --verbosity=debug
scons: Reading SConscript files ...
cuppa: core: get_option:245 [debug] option [offline] set on command-line as [True]
cuppa: version: check_current_version:21 [info] cuppa: version 0.9.24
cuppa: core: __init__:618 [info] Running in OFFLINE mode
cuppa: core: __init__:620 [info] using sconstruct file [SConstruct]
cuppa: configure: _load_conf:150 [info] No settings to load, skipping configure
cuppa: core: get_option:245 [debug] option [build_root] set using default as [_build]
cuppa: core: get_option:245 [debug] option [download_root] set using default as [_cuppa]
cuppa: core: get_option:245 [debug] option [cache_root] set using default as [~/_cuppa/_cache]
cuppa: core: get_option:245 [debug] option [runner] set using default as [process]
cuppa: core: get_option:245 [debug] option [propagate-env] set on command-line as [True]
cuppa: gcc: add_to_env:177 [debug] Adding toolchain [gcc] reported as [gcc62] with cxx_version [g++] at [/opt/rh/devtoolset-6/root/usr/bin]
Could not detect the version of libc installed. You might be missing some development libraries!
cuppa: gcc: add_to_env:177 [debug] Adding toolchain [gcc62] reported as [gcc62] with cxx_version [g++] at [/opt/rh/devtoolset-6/root/usr/bin]
cuppa: core: add_toolchains:412 [info] available toolchains are ['gcc62', 'gcc']
cuppa: core: __init__:731 [info] default profiles are ['']
cuppa: core: __init__:747 [info] default dependencies are ['']
cuppa: core: get_option:245 [debug] option [num_jobs] set on command-line as [1]
cuppa: core: build:982 [info] Using sub-sconscripts ['./src/SConscript']
cuppa: core: create_build_envs:852 [info] Default variants of ['dbg', 'rel'] being used.
cuppa: core: create_build_envs:887 [debug] propagating environment for [rel:x86_64] to all subprocesses: [{'WINDOWID': '44040199', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'PERL_MM_OPT': 'INSTALL_BASE=/home/dmsdev/perl5', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GJS_DEBUG_OUTPUT': 'stderr', 'http_proxy': 'http://localhost:3128', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'PERL_LOCAL_LIB_ROOT': ':/home/dmsdev/perl5', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'dmsdev', 'USER': 'dmsdev', 'LOG4CPP_HOME': '/home/dmsdev/log4cpp', 'PATH': '/opt/mssql-tools/bin:/etc/alternatives/java_sdk_1.8.0//bin:/opt/rh/devtoolset-6/root/usr/bin:/opt/rh/devtoolset-6/root/usr/bin:/opt/mssql-tools/bin:/etc/alternatives/java_sdk_1.8.0//bin:/opt/rh/devtoolset-6/root/usr/bin:/usr/lib64/qt-3.3/bin:/home/dmsdev/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/dmsdev/.local/bin:/home/dmsdev/bin:/opt/dev/3rd/apache-maven-2.2.1//bin:/opt/dev/3rd/gradle-3.3/bin:/home/dmsdev/Downloads/apache-tomcat-8.5.11/bin::/home/dmsdev/.local/bin:/home/dmsdev/bin:/opt/dev/3rd/apache-maven-2.2.1//bin:/opt/dev/3rd/gradle-3.3/bin:/home/dmsdev/Downloads/apache-tomcat-8.5.11/bin:', 'XDG_VTNR': '1', 'QTDIR': '/usr/lib64/qt-3.3', 'PS1': '\\u@\\h> ', 'LD_LIBRARY_PATH': '/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib:/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib:/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib', 'SSH_AGENT_PID': '3597', 'LANG': 'en_GB.utf8', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'TERM': 'screen', 'SHELL': '/bin/bash', 'XAUTHORITY': '/run/gdm/auth-for-dmsdev-iXq0hB/database', 'PCP_DIR': '/opt/rh/devtoolset-6/root', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/3390,unix/unix:/tmp/.ICE-unix/3390', 'QTINC': '/usr/lib64/qt-3.3/include', 'HISTSIZE': '1000', 'MAVEN_OPTS': '-Xms1024m -Xmx1024m -XX:MaxPermSize=1024m', 'https_proxy': 'http://localhost:3128', 'WINDOWPATH': '1', 'MANPATH': '/opt/rh/devtoolset-6/root/usr/share/man:/opt/rh/devtoolset-6/root/usr/share/man:/opt/rh/devtoolset-6/root/usr/share/man:', 'JBOSS_HOME': '/home/dmsdev/jboss', 'IMSETTINGS_INTEGRATE_DESKTOP': 'yes', 'GPG_AGENT_INFO': '/run/user/1000/keyring/gpg:0:1', 'HOME': '/home/dmsdev', 'USERNAME': 'dmsdev', 'IMSETTINGS_MODULE': 'none', 'QT_PLUGIN_PATH': '/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins', 'INFOPATH': '/opt/rh/devtoolset-6/root/usr/share/info:/opt/rh/devtoolset-6/root/usr/share/info:/opt/rh/devtoolset-6/root/usr/share/info', 'PYTHONPATH': '/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'VTE_VERSION': '3804', 'ftp_proxy': 'http://localhost:3128', 'GDMSESSION': 'gnome-classic', 'XMODIFIERS': '@im=ibus', 'GNOME_SHELL_SESSION_MODE': 'classic', 'TMUX': '/tmp/tmux-1000/default,8829,0', 'XDG_MENU_PREFIX': 'gnome-', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'QUICKFIX_HOME': '/home/dmsdev/quickfix-install2', 'XDG_CURRENT_DESKTOP': 'GNOME-Classic:GNOME', 'XDG_SESSION_ID': '2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-otC399KjOW,guid=c98b4903492afe352f24f25b597f03c6', '_': '/usr/bin/scons', 'KDEDIRS': '/usr', 'DESKTOP_SESSION': 'gnome-classic', 'JAVA_HOME': '/etc/alternatives/java_sdk_1.8.0/', 'DISPLAY': ':0', 'OLDPWD': '/home/dmsdev/repo/timm/traxFix/cuppa', 'HOSTNAME': 'dmsdev', 'GDM_LANG': 'en_GB.utf8', 'HISTCONTROL': 'ignoredups', 'SHLVL': '3', 'PWD': '/home/dmsdev/repo/timm/traxFix/cuppa/helloCuppa', 'PERL_MB_OPT': '--install_base /home/dmsdev/perl5', 'MAIL': '/var/spool/mail/dmsdev', 'XDG_SESSION_DESKTOP': 'gnome-classic', 'PERL5LIB': '/opt/rh/devtoolset-6/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-6/root/usr/lib/perl5:/opt/rh/devtoolset-6/root//usr/share/perl5/vendor_perl:/opt/rh/devtoolset-6/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-6/root/usr/lib/perl5:/opt/rh/devtoolset-6/root//usr/share/perl5/vendor_perl:/opt/rh/devtoolset-6/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-6/root/usr/lib/perl5:/opt/rh/devtoolset-6/root//usr/share/perl5/vendor_perl:/home/dmsdev/perl5/lib/perl5:', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'TMUX_PANE': '%9', 'XDG_SEAT': 'seat0'}]
cuppa: core: create_build_envs:894 [debug] propagating PATH for [rel:x86_64] to all subprocesses: ['/usr/local/bin', '/opt/bin', '/bin', '/usr/bin', '/opt/mssql-tools/bin', '/etc/alternatives/java_sdk_1.8.0//bin', '/opt/rh/devtoolset-6/root/usr/bin', '/usr/lib64/qt-3.3/bin', '/home/dmsdev/perl5/bin', '/usr/local/sbin', '/usr/sbin', '/sbin', '/home/dmsdev/.local/bin', '/home/dmsdev/bin', '/opt/dev/3rd/apache-maven-2.2.1//bin', '/opt/dev/3rd/gradle-3.3/bin', '/home/dmsdev/Downloads/apache-tomcat-8.5.11/bin', '']
cuppa: core: create_build_envs:887 [debug] propagating environment for [dbg:x86_64] to all subprocesses: [{'WINDOWID': '44040199', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'PERL_MM_OPT': 'INSTALL_BASE=/home/dmsdev/perl5', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GJS_DEBUG_OUTPUT': 'stderr', 'http_proxy': 'http://localhost:3128', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'PERL_LOCAL_LIB_ROOT': ':/home/dmsdev/perl5', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'dmsdev', 'USER': 'dmsdev', 'LOG4CPP_HOME': '/home/dmsdev/log4cpp', 'PATH': '/opt/mssql-tools/bin:/etc/alternatives/java_sdk_1.8.0//bin:/opt/rh/devtoolset-6/root/usr/bin:/opt/rh/devtoolset-6/root/usr/bin:/opt/mssql-tools/bin:/etc/alternatives/java_sdk_1.8.0//bin:/opt/rh/devtoolset-6/root/usr/bin:/usr/lib64/qt-3.3/bin:/home/dmsdev/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/dmsdev/.local/bin:/home/dmsdev/bin:/opt/dev/3rd/apache-maven-2.2.1//bin:/opt/dev/3rd/gradle-3.3/bin:/home/dmsdev/Downloads/apache-tomcat-8.5.11/bin::/home/dmsdev/.local/bin:/home/dmsdev/bin:/opt/dev/3rd/apache-maven-2.2.1//bin:/opt/dev/3rd/gradle-3.3/bin:/home/dmsdev/Downloads/apache-tomcat-8.5.11/bin:', 'XDG_VTNR': '1', 'QTDIR': '/usr/lib64/qt-3.3', 'PS1': '\\u@\\h> ', 'LD_LIBRARY_PATH': '/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib:/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib:/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib', 'SSH_AGENT_PID': '3597', 'LANG': 'en_GB.utf8', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'TERM': 'screen', 'SHELL': '/bin/bash', 'XAUTHORITY': '/run/gdm/auth-for-dmsdev-iXq0hB/database', 'PCP_DIR': '/opt/rh/devtoolset-6/root', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/3390,unix/unix:/tmp/.ICE-unix/3390', 'QTINC': '/usr/lib64/qt-3.3/include', 'HISTSIZE': '1000', 'MAVEN_OPTS': '-Xms1024m -Xmx1024m -XX:MaxPermSize=1024m', 'https_proxy': 'http://localhost:3128', 'WINDOWPATH': '1', 'MANPATH': '/opt/rh/devtoolset-6/root/usr/share/man:/opt/rh/devtoolset-6/root/usr/share/man:/opt/rh/devtoolset-6/root/usr/share/man:', 'JBOSS_HOME': '/home/dmsdev/jboss', 'IMSETTINGS_INTEGRATE_DESKTOP': 'yes', 'GPG_AGENT_INFO': '/run/user/1000/keyring/gpg:0:1', 'HOME': '/home/dmsdev', 'USERNAME': 'dmsdev', 'IMSETTINGS_MODULE': 'none', 'QT_PLUGIN_PATH': '/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins', 'INFOPATH': '/opt/rh/devtoolset-6/root/usr/share/info:/opt/rh/devtoolset-6/root/usr/share/info:/opt/rh/devtoolset-6/root/usr/share/info', 'PYTHONPATH': '/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'VTE_VERSION': '3804', 'ftp_proxy': 'http://localhost:3128', 'GDMSESSION': 'gnome-classic', 'XMODIFIERS': '@im=ibus', 'GNOME_SHELL_SESSION_MODE': 'classic', 'TMUX': '/tmp/tmux-1000/default,8829,0', 'XDG_MENU_PREFIX': 'gnome-', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'QUICKFIX_HOME': '/home/dmsdev/quickfix-install2', 'XDG_CURRENT_DESKTOP': 'GNOME-Classic:GNOME', 'XDG_SESSION_ID': '2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-otC399KjOW,guid=c98b4903492afe352f24f25b597f03c6', '_': '/usr/bin/scons', 'KDEDIRS': '/usr', 'DESKTOP_SESSION': 'gnome-classic', 'JAVA_HOME': '/etc/alternatives/java_sdk_1.8.0/', 'DISPLAY': ':0', 'OLDPWD': '/home/dmsdev/repo/timm/traxFix/cuppa', 'HOSTNAME': 'dmsdev', 'GDM_LANG': 'en_GB.utf8', 'HISTCONTROL': 'ignoredups', 'SHLVL': '3', 'PWD': '/home/dmsdev/repo/timm/traxFix/cuppa/helloCuppa', 'PERL_MB_OPT': '--install_base /home/dmsdev/perl5', 'MAIL': '/var/spool/mail/dmsdev', 'XDG_SESSION_DESKTOP': 'gnome-classic', 'PERL5LIB': '/opt/rh/devtoolset-6/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-6/root/usr/lib/perl5:/opt/rh/devtoolset-6/root//usr/share/perl5/vendor_perl:/opt/rh/devtoolset-6/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-6/root/usr/lib/perl5:/opt/rh/devtoolset-6/root//usr/share/perl5/vendor_perl:/opt/rh/devtoolset-6/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-6/root/usr/lib/perl5:/opt/rh/devtoolset-6/root//usr/share/perl5/vendor_perl:/home/dmsdev/perl5/lib/perl5:', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'TMUX_PANE': '%9', 'XDG_SEAT': 'seat0'}]
cuppa: core: create_build_envs:894 [debug] propagating PATH for [dbg:x86_64] to all subprocesses: ['/usr/local/bin', '/opt/bin', '/bin', '/usr/bin', '/opt/mssql-tools/bin', '/etc/alternatives/java_sdk_1.8.0//bin', '/opt/rh/devtoolset-6/root/usr/bin', '/usr/lib64/qt-3.3/bin', '/home/dmsdev/perl5/bin', '/usr/local/sbin', '/usr/sbin', '/sbin', '/home/dmsdev/.local/bin', '/home/dmsdev/bin', '/opt/dev/3rd/apache-maven-2.2.1//bin', '/opt/dev/3rd/gradle-3.3/bin', '/home/dmsdev/Downloads/apache-tomcat-8.5.11/bin', '']
cuppa: core: call_project_sconscript_files:1048 [debug] project exists and added to build [./src/SConscript] using [gcc62,rel,x86_64]
cuppa: core: call_project_sconscript_files:1048 [debug] project exists and added to build [./src/SConscript] using [gcc62,dbg,x86_64]
scons: done reading SConscript files.
scons: Building targets ...
Progress( SconstructBegin )
Progress( Begin sconscript: [./src/SConscript] )
Progress( Starting variant: [_build/src/gcc62/rel/x86_64/c++1z] )
g++ -o _build/src/gcc62/rel/x86_64/c++1z/working/_build/src/gcc62/rel/x86_64/c++1z/working/hello.o -c -std=c++1z -fexceptions -Wall -g -O3 -rdynamic -DNDEBUG -I. -I_build/src/gcc62/rel/x86_64/c++1z/working -Isrc -I_build/src/gcc62/rel/x86_64/c++1z/working/src -Isrc/src src/hello.cpp
g++: error: unrecognized command line option ‘-std=c++1z’
 === Process Terminated with status 1 (Elapsed 0.0161039829254s) === 

scons: *** [_build/src/gcc62/rel/x86_64/c++1z/working/_build/src/gcc62/rel/x86_64/c++1z/working/hello.o] Error 1
scons: building terminated because of errors.
dmsdev@dmsdev>
```

**Comment by ja11sop** [comment]
Really the current implementation of `--propagate-path` should really be called `--merge-path` and `--propagate-path` should be implemented to replace the existing path. I'll add both variants so there is a choice of behaviour.

**Comment by ja11sop** [comment]
The current behaviour has been changed to `--merge-path`. Now `--propagate-path` should exhibit the desired behaviour. Closing this for now but please as for it to be re-opened if the change still does not address the issue.
